---
title: "控制原理"
author: "HarryZhu"
date: "December 30, 2014"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: pdflatex
  html_document: default
  word_document: default
---


* 表征轨迹运动：绕位置转动的3自由度

* 表征姿态运动：绕质心转动的3自由度
    
    姿态角+姿态角速度

* （导航）轨道确定：航天器在空间的位置、速度如何。

* （制导）航天器轨道控制：对质心施加一定外力。
  1. 轨道机动：从一个轨道到另一个轨道的控制问题
  2. 轨道保持：克服其他干扰，保证轨道参数不变
  3. 轨道交会：两个航天器在同一时间到达同一位置
  4. 再入返回控制：脱离原来轨道，返回地球
  
*  开普勒基本定律（回答行星轨道“是什么”）
    
    1. 第一定律：椭圆律；远日点、近日点;
    
    2. 第二定律：面积律:面积速度守恒；
    
    $dA/dt=C$
    
    3. 第三定律：周期律：周期与形状无关，与半长轴有关；

    $da^3/dT^2=K$
    
*   万有引力引律

二体轨道力学和运动方程

1. N体问题到二体问题
  外力：阻力、推力、太阳辐射压力、摄动力
  
  牛顿第二定律
  
  $F = m(t) dv/dt +v(t) dm/dt$
  
  1)物体排出质量以产生推力
  
  2)相对量有关效应导致质量随时间变化；速度接近光速，质量接近无穷大
  
  H1：无动力飞行时，质量无明显变化 $dm=0$
  
  H2: 阻力和外力不存在；$m1$表示航天器质量
  
  $h^2 =miu r + r B cosv$
  
2. 二体轨道运动参数

轨道描述
1. 坐标系
2. 时间系统
3. 经典轨道要素
4. 星下点轨迹与典型轨道

3. 航天器的轨道摄动
    摄动方程
    只有二体：月心引力对轨道根数的摄动变化
    轨道根数：

#### 相对轨道动力学方程

相对轨道：两个航天器之间的相对运动；参考航天器、伴随航天器

姿态敏感器
1.地球为基准
2.天体为基准
3.惯性空间为基准
4.地面站为基准

1.光学测量；太阳；红外；星；
2.陀螺仪；加速度计
3.射频敏感器
4.磁强计

星敏感器：以恒星为惯性系（北斗星）
1.精度高1''
2.信号弱 零等星照度低；
3.克服地球、太阳杂关的干扰
3.需要恒星识别
4.能够提供三轴姿态信号

恒星光学特性
1.恒星的光谱
探测器灵敏度不同；
OBAFGK：恒星星等：恒星亮度
2.恒星分布


执行器

推进器 （非线性控制）
飞轮
磁力矩器
控制器
推力经过质心：轨控力
推力不经过质心：姿控力
F= mV +Sp
比冲=比推力：推力与损耗质量比
比推力取决于有效排气速度；

控制器
      1.星载计算机：
            1.星上控制
                1.卫星姿态、轨道控制
                2.卫星状态管理
                3.星上时间
            2.卫星测控
            3.星上数据处理 控制、任务
                1.卡尔曼滤波器
                2.星图识别
                3.轨道参数
      2.航天控制器任务
      3.被动式
      4.主动式
      
      软故障：SEU单粒子翻转：高能粒子冲击的扰动
      1.电路影响
      2.逻辑错误
      3.存储器错误
      4.丢失同步信号
      
      硬故障：单粒子闭锁效应：永久性损伤
      1.CMOS电路短路
      2.闭锁热应力的过载
      
      故障检测与修复；具有冗余结构
      FPGA可编程逻辑阵点（刷新，修改配置，重启）
      
      姿态控制系统
      
      姿态稳定：成像、轨道控制、通信；控制指标：指向精度（o）、稳定度(o/s);环境力矩、太阳帆摆
      姿态机动：区域凝视、目标跟踪、观测目标变化