---
title: "AHP层次分析法"
author: "HarryZhu"
date: "October 11, 2014"
output: html_document
---

## 1.问题来源： 

在复杂环境下，变数相互影响，难以判断最终结果

## 2.层次分析法（AHP）的思想

* 分层次考虑复杂因素对最终结果的影响情况

最高目标决策层：A

中间规则层：B1 B2 B3

最低指标层：C1 C2 C3 C4 C5

> wiki https://en.wikipedia.org/wiki/Analytic_Hierarchy_Process

## 3.开始编程

```{r,echo=TRUE}

AHP <- function(判别矩阵, 影响因素) {
  
 ## 初始化判断矩阵  
  
  rownames(判别矩阵) <- 影响因素
  
  colnames(判别矩阵) <- row.names(判别矩阵)
  
  n = nrow(判别矩阵)
  
  同阶随机一致性指标RI <- c(0, 0, 0.58, 0.9, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49, 1.52, 1.54, 1.56, 1.58, 1.59)
  
  ## 计算最大特征值  
  分母 <- matrix(rep(apply(判别矩阵, 2, sum), 3), 3, 3, byrow = TRUE)
  
  归一化矩阵 <- 判别矩阵/分母
  
  特征向量 <- apply(归一化矩阵, 1, mean)
  
  AW <- (判别矩阵 %*% 特征向量)

  最大特征值 <- sum((AW/(特征向量 * n)))
  
  ## 层次单排序的一致性检验
  
  一致性检验CI = (最大特征值 - n)/(n - 1)

  随机一致性指标CR = 一致性检验CI/同阶随机一致性指标RI[n]
  
  if (随机一致性指标CR >= 0.1) {
    print("指标CR>=0.1,请修改判断矩阵,判断矩阵的主观偏好性过强")
  }
  
  ## 输出结果
  
cat("最大特征值λmax=", 最大特征值, "一致性检验CI=", 一致性检验CI, "随机一致性指标CR", 
      随机一致性指标CR, "同阶随机一致性指标RI=", 同阶随机一致性指标RI[n])

   判别矩阵
}
```

## 4.仿真过程

```{r}

judgement <- matrix(c(1, 3, 4, (1/3), 1, 3, (1/4), (1/3), 1), 3, 3, byrow = TRUE)

factor <- c("生态", "经济", "社会")

AHP(judgement,factor)

```


